version: "3"

services:

  postgres:
    container_name: postgres
    restart: always
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

  app:
    container_name: app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    volumes:
      - ./src/:/src/
    environment:
      - FLASK_PORT=${FLASK_PORT}
      - APP_ENV=${APP_ENV}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
