version: "3"

services:

  postgres:
    container_name: postgres
    restart: always
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - 5432:5432

  api_service:
    container_name: api_service
    restart: always
    build:
      context: api/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./api/src/:/src/
    env_file:
      - ./api/.env
    depends_on:
      - postgres

  frontend_service:
    container_name: frontend_service
    restart: always
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./frontend/src/:/src/
    env_file:
      - ./frontend/.env
    depends_on:
      - api_service
